version: '3'

services:
  redis:
    restart: "no"
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    logging:
      driver: none

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    environment:
      - REDIS_HOST=redis
    env_file:
      - web/.env
    depends_on:
      - redis
    ports:
      - 3000:3000

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    environment:
      - REDIS_HOST=redis
    env_file:
      - engine/.env
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
