msg:
  export $(xargs <.env) && \
  cat msg.example.json | base64 | dune exec tokenbot msg

feed:
  export $(xargs <.env) && \
  dune exec tokenbot feed 10

scoreboard:
  export $(xargs <.env) && \
  dune exec tokenbot scoreboard 10

highscoreboard:
  export $(xargs <.env) && \
  dune exec tokenbot highscoreboard 10
