apiVersion: v1
kind: Secret
metadata:
  name: redis-bkup
  labels: {{ include "tokenbot.labels" . | nindent 4 }}
type: Opaque
data:
  redis-dump.sh: {{ tpl (.Files.Get "files/redis_dump.tpl") . | b64enc }}
  gcs-upload.sh: {{ tpl (.Files.Get "files/gcs-upload.tpl") . | b64enc }}