{{- with .Values.server -}}
{{- if .configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configMap.name | default "tokenbot-bot-cm" }}
data:
{{- .configMap.data | toYaml | nindent 2 }}
{{- end }}
{{- end }}
---
{{- with .Values.client -}}
{{- if .configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configMap.name | default "tokenbot-web-cm" }}
data:
{{- .configMap.data | toYaml | nindent 2 }}
{{- end }}
{{- end }}