{{- with .Values.bot.secrets -}}
{{- range $k, $v := . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $k }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
{{- if $.Values.clusterSecretStore }}
    name: {{ .Values.clusterSecretStore | default "gcpsm-clustersecretstore-cyderes-dev" }}
{{- else if eq "development" $.Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- else if eq "production" $.Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-prod
{{- else }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- end }}
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ $k }}
    template:
      engineVersion: v2
      metadata:
        labels:
          externalSecretsManaged: "true"
  data:
  {{- range $secretKey,$remoteKey := $v }}
  - secretKey: {{ $secretKey }}
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: {{ $remoteKey }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- with .Values.web.secrets -}}
{{- range $k, $v := . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $k }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
{{- if $.Values.clusterSecretStore }}
    name: {{ .Values.clusterSecretStore | default "gcpsm-clustersecretstore-cyderes-dev" }}
{{- else if eq "development" $.Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- else if eq "production" $.Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-prod
{{- else }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- end }}
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ $k }}
    template:
      engineVersion: v2
      metadata:
        labels:
          externalSecretsManaged: "true"
  data:
  {{- range $secretKey,$remoteKey := $v }}
  - secretKey: {{ $secretKey }}
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: {{ $remoteKey }}
  {{- end }}
{{- end }}
{{- end }}