{{- if .Values.imagePullSecrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-json-key
spec:
  refreshInterval: "1h"
  secretStoreRef:
{{- if .Values.clusterSecretStore }}
    name: {{ .Values.clusterSecretStore | default "gcpsm-clustersecretstore-cyderes-dev" }}
{{- else if eq "development" .Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- else if eq "production" .Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-prod
{{- else if eq "stage" .Values.environment }}
    name: gcpsm-clustersecretstore-cyderes-prod
{{- else }}
    name: gcpsm-clustersecretstore-cyderes-dev
{{- end }}
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
{{- with (index .Values.imagePullSecrets 0) }}
    name: {{ .name }}
{{- end }}
    template:
      engineVersion: v2
      metadata:
        labels:
          externalSecretsManaged: "true"
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: gcr-json-key_dockerconfigjson
{{- end -}}
{{- if and .Values.imagePullSecrets (eq "stage" .Values.environment ) -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-json-key-stage
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcpsm-clustersecretstore-cyderes-prod
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
{{- with (index .Values.imagePullSecrets 0) }}
    name: {{ .name }}
{{- end }}
    template:
      engineVersion: v2
      metadata:
        labels:
          externalSecretsManaged: "true"
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: gcr-json-key-stage_dockerconfigjson
{{- end -}}