{{- $fullName := include "tokenbot.fullname" . -}}
{{- $commonLabels := .Values.commonLabels | toYaml -}}
{{- if .Values.metrics.enabled }}
{{- with .Values.metrics -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}-metrics
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/instance: {{ $fullName }}
    app.kubernetes.io/managed-by: {{ $fullName }}
    {{- .labels | toYaml | nindent 4 }}
    {{ $commonLabels }}
spec:
  endpoints:
    - path: {{ .path | default "/metrics" }}
      port: {{ .port | default "metrics" }}
      interval: {{ .interval | default "60s" }}
      scrapeTimeout: {{ .scrapeTimeout | default "10s" }}
  {{ if .namespaceSelector.matchNames -}}
  namespaceSelector:
  {{- .namespaceSelector | toYaml | nindent 4 }}
  {{ end -}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}
      app.kubernetes.io/instance: {{ $fullName }}
{{- end -}}
{{- end }}